import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

// export const products = [
//   {
//     _id: uuid(),
//     title: "You Can WIN",
//     author: "Shiv Khera",
//     price: "5000",
//     categoryName: "non-fiction",
//   },
//   {
//     _id: uuid(),
//     title: "You are Winner",
//     author: "Junaid Qureshi",
//     price: "3000",
//     categoryName: "horror",
//   },
//   {
//     _id: uuid(),
//     title: "Think and Grow Rich",
//     author: "Shiv Khera",
//     price: "1000",
//     categoryName: "fiction",
//   },
// ];

export const products = [
  {
    _id: uuid(),
    title: "Ultraboost Light Shoe",
    type: "performance shoe",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433148/shoe5_n4qrsv.webp",
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433147/shoe5a_hueilc.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433147/shoe2b_t2l1ao.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433147/shoe5a_hueilc.webp",
    description:
      "The Ultraboost Light Shoe is designed for ultimate performance and comfort. It features a lightweight construction, responsive cushioning, and a breathable upper for optimal running experience.",
    rating: 4.5,
    stock: 25,
    featured: true,
    category: "shoes",
    price: 2000,
  },
  {
    _id: uuid(),
    title: "Some Other Shoe",
    type: "casual shoe",
    image:
      "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433143/shoe1_nn4fs7.webp",
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433143/shoe_1a_wgccs1.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433143/shoe1b_w7su0b.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433144/shoe1c_tktavk.webp",
    description:
      "The Some Other Shoe is a stylish and comfortable choice for casual wear. With its trendy design and quality materials, it offers both fashion and functionality.",
    rating: 3.8,
    stock: 15,
    featured: false,
    category: "shoes",
    price: 2500,
  },
  {
    _id: uuid(),
    title: "Running Shoe",
    type: "performance shoe",
    image:
      "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433143/shoe2_a1pqcm.webp",
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433145/shoe2a_khox8v.jpg",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433147/shoe2b_t2l1ao.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433145/shoe2c_xvuipo.webp",
    description:
      "The Running Shoe is engineered for speed and agility. It provides excellent traction, cushioning, and support, making it an ideal choice for runners of all levels.",
    rating: 4.2,
    stock: 30,
    featured: true,
    category: "shoes",
    price: 1499,
  },
  {
    _id: uuid(),
    title: "Basketball Shoe",
    type: "sports shoe",
    image:
      "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433144/shoe3_rw5i3n.webp",
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433146/shoe3b_wlhomq.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433145/shoe3c_zreqy7.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433145/shoe3a_ky6om3.webp",
    description:
      "The Basketball Shoe offers exceptional performance on the court. It features enhanced ankle support, cushioning, and traction for quick cuts and explosive moves.",
    rating: 4.6,
    stock: 20,
    featured: false,
    category: "shoes",
    price: 4500,
  },
  {
    _id: uuid(),
    title: "Sneakers",
    type: "casual shoe",
    image:
      "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433147/shoe4_vbeh3h.webp",
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433146/shoe4a_s6qnpn.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433146/shoe4b_jedlon.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433147/shoe4_vbeh3h.webp",
    description:
      "The Sneakers combine style and comfort for everyday wear. With their vibrant colors and cushioned sole, they are perfect for adding a pop of color to your outfit.",
    rating: 4.0,
    stock: 35,
    featured: true,
    category: "shoes",
    price: 4200,
  },
  {
    _id: uuid(),
    title: "Running Shoe 2",
    type: "performance shoe",
    image:
      "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433147/shoe6_ad8yf0.webp",
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433148/shoe6a_g8kyho.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433148/shoe6b_cctotw.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433148/shoe6c_jlwjbh.webp",
    description:
      "The Running Shoe 2 is designed for serious runners seeking optimal performance. It features advanced cushioning, breathability, and stability for a smooth and comfortable run.",
    rating: 4.8,
    stock: 18,
    featured: true,
    category: "shoes",
    price: 1699,
  },
  {
    _id: uuid(),
    title: "Football Cleats",
    type: "sports shoe",
    image:
      "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433149/shoe7_dnaolt.webp",
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433149/shoe7a_woeiuq.jpg",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433149/shoe7b_gbfzvb.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433149/shoe7c_xxlomf.webp",
    description:
      "The Football Cleats offer superior traction and support on the field. Designed for football players, they provide stability and agility for quick cuts and explosive movements.",
    rating: 4.4,
    stock: 12,
    featured: false,
    category: "shoes",
    price: 4999,
  },
  {
    _id: uuid(),
    title: "Hiking Shoes",
    type: "outdoor shoe",
    image:
      "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433150/shoe8_kkygkb.webp",
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433149/shoe8a_ipghjn.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433151/shoe8b_jh2y29.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433149/shoe8c_roprph.webp",
    description:
      "The Hiking Shoes are built to withstand rugged terrains. With their durable construction, waterproof features, and reliable grip, they are perfect for outdoor adventures.",
    rating: 4.7,
    stock: 8,
    featured: true,
    category: "shoes",
    price: 3200,
  },
  {
    _id: uuid(),
    title: "Skate Shoes",
    type: "casual shoe",
    image:
      "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433150/shoe9_avevlu.webp",
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433150/shoe9a_inmq7f.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433151/shoe9b_nynngz.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433150/shoe9c_apvsay.webp",
    description:
      "The Skate Shoes are designed for skateboarders seeking durability and board feel. With their reinforced construction and grippy outsole, they provide optimal performance on the board.",
    rating: 4.3,
    stock: 22,
    featured: false,
    category: "shoes",
    price: 2200,
  },
  {
    _id: uuid(),
    title: "Tennis Shoes",
    type: "sports shoe",
    image:
      "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433150/shoe10_jbilms.webp",
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433151/shoe10a_wio8co.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433151/shoe10b_ldnja9.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684433151/shoe10c_rsomgb.webp",
    description:
      "The Tennis Shoes are designed for performance and agility on the tennis court. With their lightweight design, cushioning, and lateral stability, they help enhance your game.",
    rating: 4.5,
    stock: 30,
    featured: true,
    category: "shoes",
    price: 3600,
  },
  {
    _id: uuid(),
    title: "Basic White T-Shirt",
    type: "casual t-shirt",
    featured: true,
    category: "t-shirts",
    price: 799,
    rating: 4.2,
    stock: 50,
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586397/tshirt1_sfbyd3.webp",
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586397/tshirt1a_rgsafi.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586398/tshirt1b_vlhdf1.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586397/tshirt1c_swyvbv.webp",
    description:
      "The Basic White T-Shirt is a wardrobe essential. Made from soft and breathable fabric, it offers comfort and versatility for everyday wear.",
  },
  {
    _id: uuid(),
    title: "Graphic Print T-Shirt",
    type: "casual t-shirt",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586397/tshirt2_uyxwo6.webp",
    featured: false,
    category: "t-shirts",
    price: 1500,
    rating: 4.5,
    stock: 30,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586398/tshirt2a_zn8yel.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586398/tshirt2b_oq24il.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586398/tshirt2c_g2fxz3.webp",
    description:
      "The Graphic Print T-Shirt features a unique and eye-catching design. Made from high-quality materials, it combines style and comfort.",
  },
  {
    _id: uuid(),
    title: "V-Neck T-Shirt",
    type: "casual t-shirt",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586398/tshirt3_uihdfg.webp",
    featured: true,
    category: "t-shirts",
    price: 1000,
    rating: 4.0,
    stock: 40,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586398/tshirt3a_qe6yhl.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586398/tshirt3b_tr9z5x.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586399/tshirt3c_w2ucvs.jpg",
    description:
      "The V-Neck T-Shirt is a classic choice with a modern twist. Its flattering neckline and soft fabric make it a comfortable and stylish option.",
  },
  {
    _id: uuid(),
    title: "Striped Polo Shirt",
    type: "polo shirt",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586399/tshirt4_yw9zvr.webp",
    featured: false,
    category: "t-shirts",
    price: 899,
    rating: 4.3,
    stock: 20,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586399/tshirt4a_oepqm9.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586399/tshirt4b_b08a83.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586399/tshirt4c_t5fo1c.webp",
    description:
      "The Striped Polo Shirt combines a classic look with modern style. It features a stylish striped pattern and a comfortable fit for a polished appearance.",
  },
  {
    _id: uuid(),
    title: "Long Sleeve T-Shirt",
    type: "casual t-shirt",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586399/tshirt5_ymibk8.webp",
    featured: true,
    category: "t-shirts",
    price: 1200,
    rating: 4.7,
    stock: 35,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586399/tshirt5a_qh09eg.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586400/tshirt5b_ffuezo.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586399/tshirt5c_aidvlh.webp",
    description:
      "The Long Sleeve T-Shirt is perfect for cooler days. It offers both comfort and style with its long sleeves and versatile design.",
  },
  {
    _id: uuid(),
    title: "Athletic Performance Shirt",
    type: "performance t-shirt",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586400/tshirt6_ecequ6.webp",
    featured: true,
    category: "t-shirts",
    price: 2100,
    rating: 4.8,
    stock: 15,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586400/tshirt6a_fa9t8n.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586399/tshirt6b_aqnjsk.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586400/tshirt6c_ywgvna.webp",
    description:
      "The Athletic Performance Shirt is designed to enhance your athletic performance. It features moisture-wicking fabric and a comfortable fit to keep you cool and dry during workouts.",
  },
  {
    _id: uuid(),
    title: "Pocket T-Shirt",
    type: "casual t-shirt",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586400/tshirt7_fzkwki.webp",
    featured: false,
    category: "t-shirts",
    price: 999,
    rating: 4.1,
    stock: 25,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586400/tshirt7a_xpem1g.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586400/tshirt7b_ys9ttm.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586401/tshirt7c_urvonx.webp",
    description:
      "The Pocket T-Shirt offers a stylish twist with a functional pocket. Made from soft fabric, it provides comfort and convenience for everyday wear.",
  },
  {
    _id: uuid(),
    title: "Crew Neck T-Shirt",
    type: "casual t-shirt",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586401/tshirt8_rcnqzc.webp",
    featured: true,
    category: "t-shirts",
    price: 1300,
    rating: 4.4,
    stock: 45,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586401/tshirt8a_v16ehq.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586401/tshirt8b_iq1klq.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586401/tshirt8c_kwdha5.webp",
    description:
      "The Crew Neck T-Shirt is a timeless classic. Its versatile design and comfortable fit make it a go-to choice for any casual outfit.",
  },
  {
    _id: uuid(),
    title: "Printed Logo T-Shirt",
    type: "casual t-shirt",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586401/tshirt9_mr5h8x.webp",
    featured: false,
    category: "t-shirts",
    price: 1900,
    rating: 4.6,
    stock: 28,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586401/tshirt9a_eq8qum.jpg",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586401/tshirt9b_sigfcl.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586402/tshirt9c_fyvovq.webp",
    description:
      "The Printed Logo T-Shirt adds a touch of branding to your look. It features a printed logo design and a comfortable fit for everyday style.",
  },
  {
    _id: uuid(),
    title: "Sporty Raglan Shirt",
    type: "casual t-shirt",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586401/tshirt10_iqlbyq.webp",
    featured: true,
    category: "t-shirts",
    price: 700,
    rating: 4.3,
    stock: 32,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586402/tshirt10a_xmhfkd.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586402/tshirt10b_ipfrfo.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1684586402/tshirt10c_u9x8mf.webp",
    description:
      "The Sporty Raglan Shirt offers a sporty and stylish look. With its contrasting raglan sleeves and comfortable fit, it's a versatile addition to your wardrobe.",
  },
  {
    _id: uuid(),
    title: "Classic Denim Jeans",
    type: "casual jeans",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000228/lower1_mmwzfo.webp",
    featured: true,
    category: "lowers",
    price: 1400,
    rating: 4.5,
    stock: 40,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000229/lower1a_fum7tj.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000229/lower1b_xzqd2s.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000229/lower1c_cexymy.webp",
    description:
      "The Classic Denim Jeans are a timeless staple. Made from high-quality denim, they offer a comfortable fit and a versatile style for everyday wear.",
  },
  {
    _id: uuid(),
    title: "Slim Fit Chinos",
    type: "casual pants",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000228/lower2_mj5pz5.webp",
    featured: false,
    category: "lowers",
    price: 1700,
    rating: 4.3,
    stock: 30,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000229/lower2a_ajr7c9.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000229/lower2b_z4quii.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000229/lower2c_oyvwiu.webp",
    description:
      "The Slim Fit Chinos combine style and comfort. With their slim silhouette and versatile design, they are perfect for both casual and semi-formal occasions.",
  },
  {
    _id: uuid(),
    title: "Jogger Pants",
    type: "athletic pants",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000229/lower3_rfiag7.webp",
    featured: true,
    category: "lowers",
    price: 2200,
    rating: 4.7,
    stock: 35,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000230/lower3a_bl0xhv.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000229/lower3b_nwo3qy.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000229/lower3c_rw2lme.webp",
    description:
      "The Jogger Pants offer a blend of style and comfort. With their elasticized cuffs and relaxed fit, they are perfect for both workouts and casual outings.",
  },
  {
    _id: uuid(),
    title: "Cargo Shorts",
    type: "casual shorts",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000230/lower4_jqx0ip.webp",
    featured: false,
    category: "lowers",
    price: 2999,
    rating: 4.2,
    stock: 25,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000230/lower4a_prr936.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000230/lower4b_rac2wc.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000231/lower4c_beux87.webp",
    description:
      "The Cargo Shorts offer a practical and stylish option for warm weather. With multiple pockets and a comfortable fit, they are perfect for outdoor adventures.",
  },
  {
    _id: uuid(),
    title: "Sports Leggings",
    type: "athletic leggings",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000230/lower5_ly4tlk.webp",
    featured: true,
    category: "lowers",
    price: 2499,
    rating: 4.6,
    stock: 50,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000231/lower5a_u0fm93.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000231/lower5b_mo5eya.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000231/lower5c_nu24cs.webp",
    description:
      "The Sports Leggings provide comfort and flexibility during workouts. Made from moisture-wicking fabric, they offer a supportive fit for active lifestyles.",
  },
  {
    _id: uuid(),
    title: "Sweatpants",
    type: "casual pants",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000231/lower6_nnmded.webp",
    featured: true,
    category: "lowers",
    price: 2799,
    rating: 4.4,
    stock: 40,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000231/lower6a_qxecjd.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000231/lower6b_dzm3gl.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000231/lower6c_tpyeej.webp",
    description:
      "The Sweatpants are perfect for lounging or casual outings. Made from soft and cozy fabric, they provide comfort and a relaxed fit for everyday wear.",
  },
  {
    _id: uuid(),
    title: "Track Pants",
    type: "athletic pants",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000232/lower7_iipb2z.webp",
    featured: false,
    category: "lowers",
    price: 3199,
    rating: 4.3,
    stock: 30,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000232/lower7a_rnp5dm.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000231/lower7b_ps2ysw.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000232/lower7c_wwncdj.webp",
    description:
      "The Track Pants are designed for athletic performance. With their lightweight and breathable fabric, they provide comfort and freedom of movement.",
  },
  {
    _id: uuid(),
    title: "Denim Shorts",
    type: "casual shorts",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000231/lower8_hzdsxo.webp",
    featured: true,
    category: "lowers",
    price: 2699,
    rating: 4.2,
    stock: 35,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000232/lower8a_pj2hgc.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000232/lower8b_yfs9gm.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000232/lower8c_xwo43r.webp",
    description:
      "The Denim Shorts offer a classic and casual style for warm weather. Made from durable denim, they are a versatile addition to your summer wardrobe.",
  },
  {
    _id: uuid(),
    title: "Cotton Joggers",
    type: "casual pants",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000232/lower9_wwrg0q.webp",
    featured: false,
    category: "lowers",
    price: 3399,
    rating: 4.4,
    stock: 30,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000232/lower9a_wzehbq.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000233/lower9b_tkju1m.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000233/lower9c_xhjcyl.webp",
    description:
      "The Cotton Joggers combine comfort and style. Made from soft cotton fabric, they provide a relaxed fit and a versatile option for everyday wear.",
  },
  {
    _id: uuid(),
    title: "Yoga Leggings",
    type: "athletic leggings",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000232/lower10_ptnkho.webp",
    featured: true,
    category: "lowers",
    price: 2299,
    rating: 4.7,
    stock: 40,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000233/lower10a_n7jweo.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000233/lower10b_yfszjw.jpg",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685000233/lower10c_za8mhl.jpg",
    description:
      "The Yoga Leggings offer comfort and flexibility for yoga and other low-impact activities. Made from stretchy fabric, they provide a supportive fit.",
  },
  {
    _id: uuid(),
    title: "Official Match Ball",
    type: "match ball",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085517/football1_ogpfgc.jpg",
    featured: true,
    category: "football",
    price: 3999,
    rating: 4.8,
    stock: 20,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085517/football1a_t58tom.jpg",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085517/football1b_umv2ra.jpg",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085517/football1c_qys9ld.jpg",
    description:
      "The Official Match Ball is FIFA-approved and designed for optimal performance. It features high-quality construction and excellent durability for competitive matches.",
  },
  {
    _id: uuid(),
    title: "Training Cones",
    type: "training equipment",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085516/football2_nbra0q.webp",
    featured: false,
    category: "football",
    price: 1299,
    rating: 4.2,
    stock: 50,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085517/football2a_zgdvj1.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085516/football2b_shmj2e.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085517/football2c_vnkiyx.webp",
    description:
      "The Training Cones are essential for training drills and skill development. They are made from durable material and come in a set of 10.",
  },
  {
    _id: uuid(),
    title: "Goalkeeper Gloves",
    type: "goalkeeper equipment",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085517/football3_zolilk.webp",
    featured: true,
    category: "football",
    price: 3499,
    rating: 4.7,
    stock: 30,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085517/football3a_exd8wu.jpg",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085518/football3b_tpvzem.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085518/football3c_k3y0nj.jpg",
    description:
      "The Goalkeeper Gloves provide excellent grip and protection. They are designed for optimal performance in various weather conditions.",
  },
  {
    _id: uuid(),
    title: "Football Cleats",
    type: "footwear",
    image: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085517/football4_vzs4nb.webp",
    featured: false,
    category: "football",
    price: 1999,
    rating: 4.6,
    stock: 25,
    image2: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085518/football4a_pvwdar.webp",
    image3: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085518/football4b_qzzotk.webp",
    image4: "https://res.cloudinary.com/dbehxf29s/image/upload/v1685085518/football4c_drixtt.webp",
    description:
      "The Football Cleats are designed for traction and stability on the field. They offer comfort and support for quick movements and sudden stops.",
  }
];
